"""Emit the frozen detector as synthesisable Verilog.

Every threshold in the model is already an integer, and every feature is an
integer, so there is nothing to quantise on the way out: the comparisons in
the generated RTL are the same comparisons the Python scored. That is the
whole reason the features were built as integers in the first place.

What this emits is the classifier only -- the comparator tree and the vote --
because that is the part that comes from the model. The feature extraction and
the per-ID state table are fixed logic that does not change when the model is
recalibrated, and they dominate the footprint: 29.0 KiB of per-ID state against
52 bits of classifier. The module below is the 0.02 %, and the port list names
exactly what the other 99.98 % has to supply.

The vote is a population count compared against a constant, not a tree walk.
Every comparator is independent, so they all evaluate in the same cycle and the
depth of the generated logic is one comparator plus the vote reduction,
whatever the depth of the tree that produced it.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from features import CAP_DT, CAP_RATE, CAP_RATIO                # noqa: E402
from select_model import predict_tables                         # noqa: E402

# Width of each feature as the extractor actually produces it. A generated
# comparator wider than its feature is dead silicon; narrower is a bug.
WIDTHS = {
    "dt_id": 20, "dt_id_dev": 20, "dt_ratio_q6": 12, "dt_bus": 16,
    "burst": 4, "dlc": 4, "id_rate": 12, "bus_rate": 12,
    "hd": 6, "hd_dev": 6, "pl_violation": 6, "pl_popcount": 7,
}


def paths(tree, node=0, acc=None):
    """Every root-to-leaf path, as (list of (feature, threshold, take_le), verdict)."""
    acc = acc or []
    if tree["is_leaf"][node]:
        return [(list(acc), tree["value"][node])]
    f, t = tree["feature"][node], tree["threshold"][node]
    out = []
    out += paths(tree, tree["left"][node], acc + [(f, t, True)])
    out += paths(tree, tree["right"][node], acc + [(f, t, False)])
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="results/detector/model.json")
    ap.add_argument("--out", default="results/verilog/can_ids_classifier.v")
    ap.add_argument("--module", default="can_ids_classifier")
    ap.add_argument("--verify", action="store_true",
                    help="simulate the generated RTL over its entire input "
                         "space and compare against the Python model")
    args = ap.parse_args()

    with open(args.model) as fh:
        m = json.load(fh)
    cols = m["feature_names"]
    used = sorted({t["feature"][i] for t in m["trees"]
                   for i in range(len(t["feature"])) if not t["is_leaf"][i]})
    n_trees = m["n_trees"]
    need = n_trees // 2 + 1

    L = []
    A = L.append
    A(f"// Generated by src/export_verilog.py from {os.path.basename(args.model)}.")
    A(f"// Do not edit: recalibrate and regenerate.")
    A(f"//")
    A(f"// {m['cost']['internal_nodes']} comparators, {n_trees} tree"
      f"{'' if n_trees == 1 else 's'}, {need} of {n_trees} votes to flag.")
    if "calibration" in m:
        c = m["calibration"]
        A(f"// Calibrated on {c.get('clean_frames')} attack-free frames, with")
        A(f"// no attack data: thresholds are what normal traffic does plus a "
          f"margin.")
    A(f"//")
    A(f"// Every threshold is an integer and every feature is an integer, so "
      f"these")
    A(f"// comparisons are exactly the ones the Python model scored. Nothing "
      f"is")
    A(f"// quantised on the way out.")
    A(f"//")
    A(f"// Combinational. The caller supplies the features for one frame and "
      f"gets")
    A(f"// the verdict in the same cycle; register the output if the fabric "
      f"needs it.")
    A("")
    A(f"module {args.module} (")
    for i in used:
        A(f"    input  wire [{WIDTHS.get(cols[i], 16) - 1}:0] {cols[i]},")
    A(f"    output wire        attack")
    A(");")
    A("")

    A("    // one comparator per distinct (feature, threshold) pair")
    seen = {}
    for ti, t in enumerate(m["trees"]):
        for n in range(len(t["feature"])):
            if t["is_leaf"][n]:
                continue
            key = (t["feature"][n], t["threshold"][n])
            if key in seen:
                continue
            name = f"le_{cols[key[0]]}_{key[1]}"
            seen[key] = name
            w = WIDTHS.get(cols[key[0]], 16)
            A(f"    wire {name} = ({cols[key[0]]} <= {w}'d{key[1]});")
    A("")

    A("    // each tree's verdict, as the OR of the paths that reach an ATTACK leaf")
    for ti, t in enumerate(m["trees"]):
        terms = []
        for path, verdict in paths(t):
            if verdict != 1:
                continue
            lits = [(seen[(f, thr)] if le else f"!{seen[(f, thr)]}")
                    for f, thr, le in path]
            terms.append("(" + " && ".join(lits) + ")" if len(lits) > 1
                         else lits[0])
        expr = " || ".join(terms) if terms else "1'b0"
        A(f"    wire tree{ti} = {expr};")
    A("")

    if n_trees == 1:
        A("    assign attack = tree0;")
    else:
        total = " + ".join(f"tree{i}" for i in range(n_trees))
        bits = max(1, (n_trees).bit_length())
        A(f"    wire [{bits - 1}:0] votes = {total};")
        A(f"    assign attack = (votes >= {bits}'d{need});")
    A("")
    A("endmodule")
    A("")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write("\n".join(L))

    print("\n".join(L))
    print(f"wrote {args.out}")
    print(f"\nports: " + ", ".join(cols[i] for i in used))
    print(f"comparators: {len(seen)}   trees: {n_trees}   "
          f"votes needed: {need}")
    print("\nThe per-ID state table and the feature extraction are not "
          "generated here.\nThey are fixed logic that survives recalibration, "
          "and they are 29.0 KiB\nagainst this module's 52 bits. This is the "
          "0.02 %.")

    if args.verify and not verify(m, cols, used, args.out, args.module):
        raise SystemExit("the generated RTL does not match the Python model")


def verify(model, cols, used, rtl_path, module):
    """Simulate every reachable input and compare against the Python model.

    Not a sample. Both features are 12 bits, so the whole space is 16.7 M
    points, which iverilog sweeps in under a minute. An exhaustive check is
    the only one that leaves no corner for an off-by-one at a threshold to
    hide in, and threshold boundaries are exactly where a hand-written
    comparator goes wrong.
    """
    import subprocess

    import numpy as np

    if len(used) != 2:
        print("\nverification is wired for the two-feature model only; "
              "skipping")
        return True

    d = os.path.dirname(rtl_path)
    tb = os.path.join(d, "tb_exhaustive.v")
    binout = os.path.join(d, "rtl_truth.bin")
    a, b = cols[used[0]], cols[used[1]]
    wa, wb = WIDTHS.get(a, 16), WIDTHS.get(b, 16)
    na, nb = 1 << wa, 1 << wb

    with open(tb, "w") as fh:
        fh.write(f"""`timescale 1ns/1ps
module tb;
    reg [{wa - 1}:0] {a};
    reg [{wb - 1}:0] {b};
    wire attack;
    integer f, i, j;
    {module} dut (.{a}({a}), .{b}({b}), .attack(attack));
    initial begin
        f = $fopen("{binout}", "wb");
        for (i = 0; i < {na}; i = i + 1) begin
            {a} = i[{wa - 1}:0];
            for (j = 0; j < {nb}; j = j + 1) begin
                {b} = j[{wb - 1}:0];
                #1;
                $fwrite(f, "%c", attack ? 8'd1 : 8'd0);
            end
        end
        $fclose(f);
        $finish;
    end
endmodule
""")

    exe = os.path.join(d, "tb_exhaustive")
    for cmd in ([["iverilog", "-o", exe, rtl_path, tb], [exe]]):
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"\nverification could not run ({cmd[0]}): "
                  f"{(r.stderr or r.stdout).strip()[:200]}")
            return True

    rtl = np.fromfile(binout, dtype=np.uint8)
    if rtl.size != na * nb:
        print(f"\nverification produced {rtl.size} points, expected {na * nb}")
        return False

    va = np.repeat(np.arange(na, dtype=np.int32), nb)
    vb = np.tile(np.arange(nb, dtype=np.int32), na)
    X = np.zeros((va.size, len(cols)), dtype=np.int32)
    X[:, used[0]] = va
    X[:, used[1]] = vb
    py = predict_tables(model, X).astype(np.uint8)

    bad = int((py != rtl).sum())
    print(f"\nverified against the Python model over the ENTIRE input space:")
    print(f"  {va.size:,} points, {bad} mismatches")
    if bad:
        k = int(np.flatnonzero(py != rtl)[0])
        print(f"  first: {a}={va[k]} {b}={vb[k]} python={py[k]} rtl={rtl[k]}")
        return False
    print(f"  ({100.0 * py.mean():.1f} % of the input GRID flags, which is "
          f"not a false alarm rate:\n   most of a 12-bit id_rate is far above "
          f"anything real traffic reaches)")
    return True


if __name__ == "__main__":
    main()
