"""Emit synthesizable Verilog for the frozen forest, plus a bit-exact testbench.

The forest is unrolled combinationally: every internal node becomes one
magnitude comparator and the path collapses into a mux tree. The whole forest
therefore resolves in a single clock, and the majority voter is a population
count against a constant. Nothing here needs a multiplier, a divider or a state
machine.

Generated files:
  rf_forest.v      the forest and its voter
  tb_rf_forest.v   replays the test truncation and compares against Python
  vectors.txt      one line per frame: features then the expected verdict
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
from features import FEATURE_SETS                          # noqa: E402
from select_model import predict_tables                    # noqa: E402


def emit_tree(tree: dict, tree_idx: int, sig: dict) -> list[str]:
    """Combinational mux tree, written as nested conditionals."""
    lines = []
    feature = tree["feature"]
    thr = tree["threshold"]
    left, right = tree["left"], tree["right"]
    is_leaf, value = tree["is_leaf"], tree["value"]
    names = tree["feature_names"]

    # one comparator per internal node
    for n in range(len(is_leaf)):
        if is_leaf[n]:
            continue
        fname = names[feature[n]]
        w = sig[fname]
        lines.append(
            f"    wire c{tree_idx}_{n} = ({fname} <= {w}'d{thr[n]});"
        )

    def expr(n: int) -> str:
        if is_leaf[n]:
            return f"1'b{value[n]}"
        return f"(c{tree_idx}_{n} ? {expr(left[n])} : {expr(right[n])})"

    lines.append(f"    assign vote[{tree_idx}] = {expr(0)};")
    return lines


def emit_forest(model: dict) -> str:
    names = model["feature_names"]
    widths = model["feature_widths"]
    sig = dict(zip(names, widths))
    n_trees = model["n_trees"]
    majority = n_trees // 2 + 1

    ports = "\n".join(
        f"    input  wire [{w - 1}:0] {n}," for n, w in zip(names, widths)
    )
    body = []
    for i, tree in enumerate(model["trees"]):
        body.append(f"    // ---- tree {i} "
                    f"({sum(1 for x in tree['is_leaf'] if not x)} comparators)")
        body += emit_tree(tree, i, sig)
        body.append("")

    sum_terms = " + ".join(f"vote[{i}]" for i in range(n_trees))
    vote_w = max(1, int(np.ceil(np.log2(n_trees + 1))))

    return f"""// Generated by src/export_verilog.py -- do not edit by hand.
//
// Random forest CAN intrusion detector.
//   trees            {n_trees}
//   comparator nodes {model['cost']['internal_nodes']}
//   max tree depth   {model['cost']['max_depth']}
//   features         {', '.join(names)}
//
// Combinational, so the verdict is valid the cycle after the features are
// registered. Majority threshold is {majority} of {n_trees}.
`default_nettype none

module rf_forest (
    input  wire clk,
    input  wire rst_n,
    input  wire in_valid,
{ports}
    output reg  out_valid,
    output reg  attack
);

    wire [{n_trees - 1}:0] vote;

{chr(10).join(body)}
    wire [{vote_w - 1}:0] vote_count = {sum_terms};
    wire attack_comb = (vote_count >= {vote_w}'d{majority});

    always @(posedge clk) begin
        if (!rst_n) begin
            out_valid <= 1'b0;
            attack    <= 1'b0;
        end else begin
            out_valid <= in_valid;
            attack    <= attack_comb;
        end
    end

endmodule

`default_nettype wire
"""


def emit_tb(model: dict, n_vectors: int) -> str:
    names = model["feature_names"]
    widths = model["feature_widths"]
    decls = "\n".join(
        f"    reg [{w - 1}:0] {n};" for n, w in zip(names, widths)
    )
    conns = "\n".join(f"        .{n}({n})," for n in names)
    scan_args = ", ".join(names)
    fmt = " ".join(["%d"] * (len(names) + 1))
    return f"""// Generated by src/export_verilog.py -- do not edit by hand.
//
// Replays every frame of the test truncation through rf_forest and compares
// the RTL verdict against the verdict the Python integer model produced.
// Any mismatch at all fails the run.
`timescale 1ns / 1ps
`default_nettype none

module tb_rf_forest;

    reg clk = 0;
    reg rst_n = 0;
    reg in_valid = 0;
{decls}
    reg expected;

    wire out_valid;
    wire attack;

    integer fd, code, i;
    integer checked = 0;
    integer mismatches = 0;

    rf_forest dut (
        .clk(clk),
        .rst_n(rst_n),
        .in_valid(in_valid),
{conns}
        .out_valid(out_valid),
        .attack(attack)
    );

    always #5 clk = ~clk;

    initial begin
        fd = $fopen("vectors.txt", "r");
        if (fd == 0) begin
            $display("FATAL: cannot open vectors.txt");
            $finish;
        end

        @(posedge clk);
        rst_n = 1;

        for (i = 0; i < {n_vectors}; i = i + 1) begin
            code = $fscanf(fd, "{fmt}\\n", {scan_args}, expected);
            if (code != {len(names) + 1}) begin
                $display("FATAL: short read at vector %0d (code %0d)", i, code);
                $finish;
            end
            in_valid = 1;
            @(posedge clk);
            #1;
            if (attack !== expected) begin
                if (mismatches < 10)
                    $display("MISMATCH vector %0d: rtl=%b expected=%b",
                             i, attack, expected);
                mismatches = mismatches + 1;
            end
            checked = checked + 1;
        end

        in_valid = 0;
        $fclose(fd);
        $display("checked %0d vectors, %0d mismatches", checked, mismatches);
        if (mismatches == 0)
            $display("RESULT: PASS  RTL matches the Python model bit for bit");
        else
            $display("RESULT: FAIL");
        $finish;
    end

endmodule

`default_nettype wire
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="results/model.json")
    ap.add_argument("--cache", default="results/cache.npz")
    ap.add_argument("--rtl-dir", default="rtl")
    ap.add_argument("--max-vectors", type=int, default=300000,
                    help="forest testbench vectors. 0 means the whole test "
                         "truncation, which Icarus takes a very long time to "
                         "chew through")
    ap.add_argument("--raw-cache", default="",
                    help="npz holding the raw test frames, enabling the "
                         "end-to-end can_ids_top testbench")
    ap.add_argument("--max-top-vectors", type=int, default=200000)
    ap.add_argument("--baseline", default="",
                    help="baseline.json, needed for the bus rate constant")
    args = ap.parse_args()

    with open(args.model) as fh:
        model = json.load(fh)

    os.makedirs(args.rtl_dir, exist_ok=True)

    z = np.load(args.cache, allow_pickle=True)
    columns = list(z["columns"])
    cols = FEATURE_SETS[model["feature_set"]]
    idx = [columns.index(c) for c in cols]
    Xte = z["Xte"][:, idx]
    if args.max_vectors:
        Xte = Xte[: args.max_vectors]
    pred = predict_tables(model, Xte)

    forest_path = os.path.join(args.rtl_dir, "rf_forest.v")
    with open(forest_path, "w") as fh:
        fh.write(emit_forest(model))

    tb_path = os.path.join(args.rtl_dir, "tb_rf_forest.v")
    with open(tb_path, "w") as fh:
        fh.write(emit_tb(model, len(Xte)))

    vec_path = os.path.join(args.rtl_dir, "vectors.txt")
    table = np.column_stack([Xte, pred]).astype(np.int64)
    # np.savetxt formats row by row and is far too slow at this size
    with open(vec_path, "w") as fh:
        fh.write("\n".join(" ".join(map(str, row)) for row in table.tolist()))
        fh.write("\n")

    print(f"wrote {forest_path}")
    print(f"wrote {tb_path}")
    print(f"wrote {vec_path}  ({len(Xte)} vectors)")
    if args.raw_cache:
        raw = np.load(args.raw_cache, allow_pickle=True)
        # materialise once: indexing an npz member re-reads the archive
        r_id = raw["can_id"]
        r_dlc = raw["dlc"]
        r_pl = raw["payload"]
        r_ts = raw["ts_us"]
        k = min(args.max_top_vectors, len(r_id))
        top_tb = os.path.join(args.rtl_dir, "tb_can_ids_top.v")
        with open(top_tb, "w") as fh:
            bus_recip = 0
            if args.baseline:
                with open(args.baseline) as bf:
                    bl = json.load(bf)
                bi = int(bl.get("bus_interval_us", 0))
                if bi > 0:
                    bus_recip = min(int(round((1 << 16) * 64.0 / bi)), 0xFFFF)
            fh.write(emit_top_tb(k, bus_recip))
        top_vec = os.path.join(args.rtl_dir, "top_vectors.txt")
        with open(top_vec, "w") as fh:
            fh.write("".join(
                f"{int(r_id[i])} {int(r_dlc[i])} {int(r_pl[i]):016x} "
                f"{int(r_ts[i])} {int(pred[i])}\n"
                for i in range(k)
            ))
        print(f"wrote {top_tb}")
        print(f"wrote {top_vec}  ({k} frames)")

    print(f"comparators {model['cost']['internal_nodes']}, "
          f"trees {model['n_trees']}, depth {model['cost']['max_depth']}")



# --------------------------------------------------------------------------
# End-to-end testbench: raw CAN frames in, verdict out. This one exercises the
# feature extractor and the forest together, so a pass means the whole RTL
# chain reproduces the Python pipeline, not just the trained tables.
# --------------------------------------------------------------------------

TOP_TB = """// Generated by src/export_verilog.py -- do not edit by hand.
//
// Feeds raw CAN frames into can_ids_top and compares each verdict against the
// verdict the Python pipeline produced for the same frame. This covers the
// feature extractor, the per-ID state RAM, the baseline ROMs and the forest.
`timescale 1ns / 1ps
`default_nettype none

module tb_can_ids_top;

    reg clk = 0;
    reg rst_n = 0;
    reg frame_valid = 0;
    reg [10:0] can_id;
    reg [3:0]  dlc;
    reg [63:0] payload;
    reg [31:0] ts_us;
    reg        expected;

    wire busy, verdict_valid, attack;

    integer fd, code, i;
    integer checked = 0;
    integer mismatches = 0;

    can_ids_top #(.BUS_RECIP(16'dBUS_RECIP_VALUE)) dut (
        .clk(clk), .rst_n(rst_n),
        .frame_valid(frame_valid), .can_id(can_id), .dlc(dlc),
        .payload(payload), .ts_us(ts_us), .busy(busy),
        .verdict_valid(verdict_valid), .attack(attack)
    );

    always #5 clk = ~clk;

    initial begin
        fd = $fopen("top_vectors.txt", "r");
        if (fd == 0) begin
            $display("FATAL: cannot open top_vectors.txt");
            $finish;
        end

        repeat (2) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        for (i = 0; i < N_VECTORS; i = i + 1) begin
            code = $fscanf(fd, "%d %d %h %d %d\\n",
                           can_id, dlc, payload, ts_us, expected);
            if (code != 5) begin
                $display("FATAL: short read at frame %0d (code %0d)", i, code);
                $finish;
            end

            frame_valid = 1;
            @(posedge clk);
            frame_valid = 0;

            // wait for this frame's verdict
            while (!verdict_valid) @(posedge clk);
            #1;
            if (attack !== expected) begin
                if (mismatches < 10)
                    $display("MISMATCH frame %0d id=%03h: rtl=%b expected=%b",
                             i, can_id, attack, expected);
                mismatches = mismatches + 1;
            end
            checked = checked + 1;
            @(posedge clk);
        end

        $fclose(fd);
        $display("checked %0d frames, %0d mismatches", checked, mismatches);
        if (mismatches == 0)
            $display("RESULT: PASS  full RTL chain matches the Python pipeline");
        else
            $display("RESULT: FAIL");
        $finish;
    end

endmodule

`default_nettype wire
"""


def emit_top_tb(n_vectors: int, bus_recip: int) -> str:
    return (TOP_TB
            .replace("N_VECTORS", str(n_vectors))
            .replace("BUS_RECIP_VALUE", str(bus_recip)))

if __name__ == "__main__":
    main()
