// Top level of the CAN intrusion detector.
//
// One CAN frame in, one verdict out. The feature extractor takes 3 cycles and
// the forest resolves combinationally with a registered output, so the total is
// 4 cycles from frame_valid to verdict_valid.
//
// At 100 MHz that is 40 ns per frame against a 1 ms budget, a margin of 25000x.
// The design is therefore limited by CAN bus bandwidth, not by the detector.

`default_nettype none

module can_ids_top #(
    parameter ID_BITS   = 11,
    parameter BUS_RECIP = 16'd0   // set from the trained baseline
) (
    input  wire               clk,
    input  wire               rst_n,

    input  wire               frame_valid,
    input  wire [ID_BITS-1:0] can_id,
    input  wire [3:0]         dlc,
    input  wire [63:0]        payload,
    input  wire [31:0]        ts_us,
    output wire               busy,

    output wire               verdict_valid,
    output wire               attack
);

    wire        feat_valid;
    wire [19:0] f_dt_id;
    wire [19:0] f_dt_id_dev;
    wire [11:0] f_dt_ratio_q6;
    wire [6:0]  f_hd;
    wire [6:0]  f_hd_dev;
    wire [15:0] f_dt_bus;
    wire [3:0]  f_burst;
    wire        f_id_known;
    wire [ID_BITS-1:0] f_can_id;
    wire [3:0]  f_dlc;
    wire [6:0]  f_pl_violation;
    wire [6:0]  f_pl_popcount;
    wire [11:0] f_id_rate;
    wire [11:0] f_bus_rate;

    can_ids_features #(
        .ID_BITS(ID_BITS),
        .BUS_RECIP(BUS_RECIP)
    ) u_feat (
        .clk(clk),
        .rst_n(rst_n),
        .frame_valid(frame_valid),
        .can_id(can_id),
        .dlc(dlc),
        .payload(payload),
        .ts_us(ts_us),
        .busy(busy),
        .feat_valid(feat_valid),
        .f_dt_id(f_dt_id),
        .f_dt_id_dev(f_dt_id_dev),
        .f_dt_ratio_q6(f_dt_ratio_q6),
        .f_hd(f_hd),
        .f_hd_dev(f_hd_dev),
        .f_dt_bus(f_dt_bus),
        .f_burst(f_burst),
        .f_id_known(f_id_known),
        .f_can_id(f_can_id),
        .f_dlc(f_dlc),
        .f_pl_violation(f_pl_violation),
        .f_pl_popcount(f_pl_popcount),
        .f_id_rate(f_id_rate),
        .f_bus_rate(f_bus_rate)
    );

    // rf_forest.v is generated by src/export_verilog.py and only declares the
    // ports for the features the chosen model actually splits on.
    rf_forest u_forest (
        .clk(clk),
        .rst_n(rst_n),
        .in_valid(feat_valid),
        .dt_id(f_dt_id),
        .dt_id_dev(f_dt_id_dev),
        .dt_ratio_q6(f_dt_ratio_q6),
        .hd(f_hd),
        .hd_dev(f_hd_dev),
        .dt_bus(f_dt_bus),
        .burst(f_burst),
        .dlc(f_dlc),
        .pl_violation(f_pl_violation),
        .pl_popcount(f_pl_popcount),
        .id_rate(f_id_rate),
        .bus_rate(f_bus_rate),
        .out_valid(verdict_valid),
        .attack(attack)
    );

endmodule

`default_nettype wire
