// Generated by src/export_verilog.py -- do not edit by hand.
//
// Random forest CAN intrusion detector.
//   trees            3
//   comparator nodes 14
//   max tree depth   3
//   features         dt_id, dt_id_dev, dt_ratio_q6, hd, hd_dev, dt_bus, burst, dlc, pl_violation, pl_popcount, id_rate, bus_rate
//
// Combinational, so the verdict is valid the cycle after the features are
// registered. Majority threshold is 2 of 3.
`default_nettype none

module rf_forest (
    input  wire clk,
    input  wire rst_n,
    input  wire in_valid,
    input  wire [19:0] dt_id,
    input  wire [19:0] dt_id_dev,
    input  wire [11:0] dt_ratio_q6,
    input  wire [6:0] hd,
    input  wire [6:0] hd_dev,
    input  wire [15:0] dt_bus,
    input  wire [3:0] burst,
    input  wire [3:0] dlc,
    input  wire [6:0] pl_violation,
    input  wire [6:0] pl_popcount,
    input  wire [11:0] id_rate,
    input  wire [11:0] bus_rate,
    output reg  out_valid,
    output reg  attack
);

    wire [2:0] vote;

    // ---- tree 0 (6 comparators)
    wire c0_0 = (id_rate <= 12'd288);
    wire c0_1 = (dt_ratio_q6 <= 12'd12);
    wire c0_3 = (dt_bus <= 16'd3077);
    wire c0_6 = (burst <= 4'd0);
    wire c0_7 = (dt_id_dev <= 20'd8289);
    wire c0_10 = (burst <= 4'd1);
    assign vote[0] = (c0_0 ? (c0_1 ? 1'b1 : (c0_3 ? 1'b0 : 1'b0)) : (c0_6 ? (c0_7 ? 1'b0 : 1'b1) : (c0_10 ? 1'b1 : 1'b1)));

    // ---- tree 1 (4 comparators)
    wire c1_0 = (pl_popcount <= 7'd2);
    wire c1_1 = (dt_id <= 20'd1310);
    wire c1_2 = (dt_id_dev <= 20'd9711);
    wire c1_5 = (id_rate <= 12'd72);
    assign vote[1] = (c1_0 ? (c1_1 ? (c1_2 ? 1'b1 : 1'b1) : (c1_5 ? 1'b0 : 1'b0)) : 1'b0);

    // ---- tree 2 (4 comparators)
    wire c2_0 = (pl_popcount <= 7'd2);
    wire c2_1 = (dt_ratio_q6 <= 12'd9);
    wire c2_2 = (id_rate <= 12'd1978);
    wire c2_5 = (hd_dev <= 7'd0);
    assign vote[2] = (c2_0 ? (c2_1 ? (c2_2 ? 1'b1 : 1'b1) : (c2_5 ? 1'b0 : 1'b0)) : 1'b0);

    wire [1:0] vote_count = vote[0] + vote[1] + vote[2];
    wire attack_comb = (vote_count >= 2'd2);

    always @(posedge clk) begin
        if (!rst_n) begin
            out_valid <= 1'b0;
            attack    <= 1'b0;
        end else begin
            out_valid <= in_valid;
            attack    <= attack_comb;
        end
    end

endmodule

`default_nettype wire
