// Generated by src/export_verilog.py -- do not edit by hand.
//
// Feeds raw CAN frames into can_ids_top and compares each verdict against the
// verdict the Python pipeline produced for the same frame. This covers the
// feature extractor, the per-ID state RAM, the baseline ROMs and the forest.
`timescale 1ns / 1ps
`default_nettype none

module tb_can_ids_top;

    reg clk = 0;
    reg rst_n = 0;
    reg frame_valid = 0;
    reg [10:0] can_id;
    reg [3:0]  dlc;
    reg [63:0] payload;
    reg [31:0] ts_us;
    reg        expected;

    wire busy, verdict_valid, attack;

    integer fd, code, i;
    integer checked = 0;
    integer mismatches = 0;

    can_ids_top #(.BUS_RECIP(16'd16009)) dut (
        .clk(clk), .rst_n(rst_n),
        .frame_valid(frame_valid), .can_id(can_id), .dlc(dlc),
        .payload(payload), .ts_us(ts_us), .busy(busy),
        .verdict_valid(verdict_valid), .attack(attack)
    );

    always #5 clk = ~clk;

    initial begin
        fd = $fopen("top_vectors.txt", "r");
        if (fd == 0) begin
            $display("FATAL: cannot open top_vectors.txt");
            $finish;
        end

        repeat (2) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        for (i = 0; i < 200000; i = i + 1) begin
            code = $fscanf(fd, "%d %d %h %d %d\n",
                           can_id, dlc, payload, ts_us, expected);
            if (code != 5) begin
                $display("FATAL: short read at frame %0d (code %0d)", i, code);
                $finish;
            end

            frame_valid = 1;
            @(posedge clk);
            frame_valid = 0;

            // wait for this frame's verdict
            while (!verdict_valid) @(posedge clk);
            #1;
            if (attack !== expected) begin
                if (mismatches < 10)
                    $display("MISMATCH frame %0d id=%03h: rtl=%b expected=%b",
                             i, can_id, attack, expected);
                mismatches = mismatches + 1;
            end
            checked = checked + 1;
            @(posedge clk);
        end

        $fclose(fd);
        $display("checked %0d frames, %0d mismatches", checked, mismatches);
        if (mismatches == 0)
            $display("RESULT: PASS  full RTL chain matches the Python pipeline");
        else
            $display("RESULT: FAIL");
        $finish;
    end

endmodule

`default_nettype wire
