// Generated by src/export_verilog.py -- do not edit by hand.
//
// Random forest CAN intrusion detector.
//   trees            7
//   comparator nodes 19
//   max tree depth   3
//   features         dt_id, dt_id_dev, dt_ratio_q6, hd, hd_dev, dt_bus, burst, dlc, pl_violation, pl_popcount, id_rate, bus_rate
//
// Combinational, so the verdict is valid the cycle after the features are
// registered. Majority threshold is 4 of 7.
`default_nettype none

module rf_forest (
    input  wire clk,
    input  wire rst_n,
    input  wire in_valid,
    input  wire [19:0] dt_id,
    input  wire [19:0] dt_id_dev,
    input  wire [11:0] dt_ratio_q6,
    input  wire [6:0] hd,
    input  wire [6:0] hd_dev,
    input  wire [15:0] dt_bus,
    input  wire [3:0] burst,
    input  wire [3:0] dlc,
    input  wire [6:0] pl_violation,
    input  wire [6:0] pl_popcount,
    input  wire [11:0] id_rate,
    input  wire [11:0] bus_rate,
    output reg  out_valid,
    output reg  attack
);

    wire [6:0] vote;

    // ---- tree 0 (1 comparators)
    wire c0_0 = (id_rate <= 12'd143);
    assign vote[0] = (c0_0 ? 1'b0 : 1'b1);

    // ---- tree 1 (2 comparators)
    wire c1_0 = (pl_popcount <= 7'd0);
    wire c1_1 = (id_rate <= 12'd75);
    assign vote[1] = (c1_0 ? (c1_1 ? 1'b0 : 1'b1) : 1'b0);

    // ---- tree 2 (4 comparators)
    wire c2_0 = (pl_popcount <= 7'd0);
    wire c2_1 = (dt_bus <= 16'd251);
    wire c2_2 = (id_rate <= 12'd90);
    wire c2_5 = (dt_ratio_q6 <= 12'd22);
    assign vote[2] = (c2_0 ? (c2_1 ? (c2_2 ? 1'b0 : 1'b1) : (c2_5 ? 1'b1 : 1'b0)) : 1'b0);

    // ---- tree 3 (4 comparators)
    wire c3_0 = (dt_id <= 20'd6627);
    wire c3_1 = (dt_id <= 20'd1480);
    wire c3_3 = (id_rate <= 12'd399);
    wire c3_6 = (dt_ratio_q6 <= 12'd3);
    assign vote[3] = (c3_0 ? (c3_1 ? 1'b1 : (c3_3 ? 1'b0 : 1'b1)) : (c3_6 ? 1'b1 : 1'b0));

    // ---- tree 4 (1 comparators)
    wire c4_0 = (id_rate <= 12'd143);
    assign vote[4] = (c4_0 ? 1'b0 : 1'b1);

    // ---- tree 5 (6 comparators)
    wire c5_0 = (dt_id <= 20'd6627);
    wire c5_1 = (dt_id_dev <= 20'd6497);
    wire c5_2 = (dt_ratio_q6 <= 12'd11);
    wire c5_5 = (pl_popcount <= 7'd0);
    wire c5_8 = (burst <= 4'd0);
    wire c5_10 = (dt_id_dev <= 20'd5003);
    assign vote[5] = (c5_0 ? (c5_1 ? (c5_2 ? 1'b1 : 1'b0) : (c5_5 ? 1'b1 : 1'b0)) : (c5_8 ? 1'b0 : (c5_10 ? 1'b0 : 1'b1)));

    // ---- tree 6 (1 comparators)
    wire c6_0 = (dt_ratio_q6 <= 12'd0);
    assign vote[6] = (c6_0 ? 1'b1 : 1'b0);

    wire [2:0] vote_count = vote[0] + vote[1] + vote[2] + vote[3] + vote[4] + vote[5] + vote[6];
    wire attack_comb = (vote_count >= 3'd4);

    always @(posedge clk) begin
        if (!rst_n) begin
            out_valid <= 1'b0;
            attack    <= 1'b0;
        end else begin
            out_valid <= in_valid;
            attack    <= attack_comb;
        end
    end

endmodule

`default_nettype wire
