// Generated by src/export_verilog.py -- do not edit by hand.
//
// Random forest CAN intrusion detector.
//   trees            3
//   comparator nodes 12
//   max tree depth   5
//   features         dt_id, dt_id_dev, dt_ratio_q6, hd, hd_dev, dt_bus, burst, dlc, pl_violation, pl_popcount
//
// Combinational, so the verdict is valid the cycle after the features are
// registered. Majority threshold is 2 of 3.
`default_nettype none

module rf_forest (
    input  wire clk,
    input  wire rst_n,
    input  wire in_valid,
    input  wire [19:0] dt_id,
    input  wire [19:0] dt_id_dev,
    input  wire [11:0] dt_ratio_q6,
    input  wire [6:0] hd,
    input  wire [6:0] hd_dev,
    input  wire [15:0] dt_bus,
    input  wire [3:0] burst,
    input  wire [3:0] dlc,
    input  wire [6:0] pl_violation,
    input  wire [6:0] pl_popcount,
    output reg  out_valid,
    output reg  attack
);

    wire [2:0] vote;

    // ---- tree 0 (2 comparators)
    wire c0_0 = (pl_popcount <= 7'd0);
    wire c0_1 = (dt_id <= 20'd24085);
    assign vote[0] = (c0_0 ? (c0_1 ? 1'b1 : 1'b0) : 1'b0);

    // ---- tree 1 (2 comparators)
    wire c1_0 = (pl_popcount <= 7'd0);
    wire c1_1 = (dlc <= 4'd5);
    assign vote[1] = (c1_0 ? (c1_1 ? 1'b0 : 1'b1) : 1'b0);

    // ---- tree 2 (8 comparators)
    wire c2_0 = (burst <= 4'd0);
    wire c2_1 = (pl_popcount <= 7'd0);
    wire c2_2 = (dt_ratio_q6 <= 12'd52);
    wire c2_6 = (hd <= 7'd0);
    wire c2_7 = (pl_popcount <= 7'd5);
    wire c2_10 = (hd_dev <= 7'd11);
    wire c2_12 = (dt_id_dev <= 20'd9829);
    wire c2_14 = (pl_violation <= 7'd3);
    assign vote[2] = (c2_0 ? (c2_1 ? (c2_2 ? 1'b1 : 1'b0) : 1'b0) : (c2_6 ? (c2_7 ? 1'b1 : 1'b0) : (c2_10 ? 1'b0 : (c2_12 ? 1'b1 : (c2_14 ? 1'b0 : 1'b1)))));

    wire [1:0] vote_count = vote[0] + vote[1] + vote[2];
    wire attack_comb = (vote_count >= 2'd2);

    always @(posedge clk) begin
        if (!rst_n) begin
            out_valid <= 1'b0;
            attack    <= 1'b0;
        end else begin
            out_valid <= in_valid;
            attack    <= attack_comb;
        end
    end

endmodule

`default_nettype wire
