// Generated by src/export_verilog.py -- do not edit by hand.
//
// Replays every frame of the test truncation through rf_forest and compares
// the RTL verdict against the verdict the Python integer model produced.
// Any mismatch at all fails the run.
`timescale 1ns / 1ps
`default_nettype none

module tb_rf_forest;

    reg clk = 0;
    reg rst_n = 0;
    reg in_valid = 0;
    reg [19:0] dt_id;
    reg [19:0] dt_id_dev;
    reg [11:0] dt_ratio_q6;
    reg [6:0] hd;
    reg [6:0] hd_dev;
    reg [15:0] dt_bus;
    reg [3:0] burst;
    reg [3:0] dlc;
    reg [6:0] pl_violation;
    reg [6:0] pl_popcount;
    reg expected;

    wire out_valid;
    wire attack;

    integer fd, code, i;
    integer checked = 0;
    integer mismatches = 0;

    rf_forest dut (
        .clk(clk),
        .rst_n(rst_n),
        .in_valid(in_valid),
        .dt_id(dt_id),
        .dt_id_dev(dt_id_dev),
        .dt_ratio_q6(dt_ratio_q6),
        .hd(hd),
        .hd_dev(hd_dev),
        .dt_bus(dt_bus),
        .burst(burst),
        .dlc(dlc),
        .pl_violation(pl_violation),
        .pl_popcount(pl_popcount),
        .out_valid(out_valid),
        .attack(attack)
    );

    always #5 clk = ~clk;

    initial begin
        fd = $fopen("vectors.txt", "r");
        if (fd == 0) begin
            $display("FATAL: cannot open vectors.txt");
            $finish;
        end

        @(posedge clk);
        rst_n = 1;

        for (i = 0; i < 300000; i = i + 1) begin
            code = $fscanf(fd, "%d %d %d %d %d %d %d %d %d %d %d\n", dt_id, dt_id_dev, dt_ratio_q6, hd, hd_dev, dt_bus, burst, dlc, pl_violation, pl_popcount, expected);
            if (code != 11) begin
                $display("FATAL: short read at vector %0d (code %0d)", i, code);
                $finish;
            end
            in_valid = 1;
            @(posedge clk);
            #1;
            if (attack !== expected) begin
                if (mismatches < 10)
                    $display("MISMATCH vector %0d: rtl=%b expected=%b",
                             i, attack, expected);
                mismatches = mismatches + 1;
            end
            checked = checked + 1;
        end

        in_valid = 0;
        $fclose(fd);
        $display("checked %0d vectors, %0d mismatches", checked, mismatches);
        if (mismatches == 0)
            $display("RESULT: PASS  RTL matches the Python model bit for bit");
        else
            $display("RESULT: FAIL");
        $finish;
    end

endmodule

`default_nettype wire
